import 'dart:convert';
import 'dart:js_interop';

import 'package:web/web.dart' as web;

import 'update_checker.dart';

/// Web [UpdateChecker]: fetches `version.json` (generated by
/// `flutter build web` next to `index.html`) with caching disabled.
UpdateChecker createUpdateChecker() => WebUpdateChecker();

class WebUpdateChecker extends UpdateChecker {
  /// Version of the running build, injected at build time:
  /// `flutter build web --dart-define=APP_VERSION=$(git rev-parse --short HEAD)`
  /// Falls back to 'dev' for local runs without the define.
  static const String _running =
      String.fromEnvironment('APP_VERSION', defaultValue: 'dev');

  @override
  String get runningVersion => _running;

  @override
  Future<String?> fetchServerVersion() async {
    try {
      // Cache-buster query defeats intermediary caches even when the server
      // ignores the no-cache request directive.
      final url =
          'version.json?_=${DateTime.now().millisecondsSinceEpoch}';
      final response = await web.window
          .fetch(url.toJS, web.RequestInit(cache: 'no-cache'))
          .toDart;
      if (!response.ok) return null;
      final body = (await response.text().toDart).toDart;
      final json = jsonDecode(body) as Map<String, dynamic>;
      // version.json is generated by `flutter build web` from pubspec.yaml's
      // `version: X.Y.Z+N` -> {"version": "X.Y.Z", "build_number": "N"}.
      // APP_VERSION must be set to the same X.Y.Z+N at build time.
      final version = json['version'];
      final build = json['build_number'];
      if (version is! String || build is! String) return null;
      return '$version+$build';
    } catch (_) {
      return null;
    }
  }
}
